apiVersion: scalebeyond.rejekts.io/v1alpha1
kind: Concierge
metadata:
  name: concierge
  namespace: default
spec:
  parameters:
    lobby: zero
    name: concierge.infinite-hotel.de
    gateguard: gateguard.infinite-hotel.de
