apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: tenants.scalebeyond.rejekts.io
spec:
  compositeTypeRef:
    apiVersion: scalebeyond.rejekts.io/v1alpha1
    kind: XTenant
  mode: Pipeline
  pipeline:
  - functionRef:
      name: infinite-hotel-conceptualtenants
    step: tenants
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
