apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: floors.scalebeyond.rejekts.io
spec:
  compositeTypeRef:
    apiVersion: scalebeyond.rejekts.io/v1alpha1
    kind: XFloor
  mode: Pipeline
  pipeline:
  - functionRef:
      name: infinite-hotel-conceptualfloor
    step: floor
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
