apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xguests.scalebeyond.rejekts.io
spec:
  compositeTypeRef:
    apiVersion: scalebeyond.rejekts.io/v1alpha1
    kind: XGuest
  mode: Pipeline
  pipeline:
  - functionRef:
      name: infinite-hotel-conceptualxguest
    step: xguest
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
