apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xlobbies.scalebeyond.rejekts.io
spec:
  compositeTypeRef:
    apiVersion: scalebeyond.rejekts.io/v1alpha1
    kind: XLobby
  mode: Pipeline
  pipeline:
  - functionRef:
      name: infinite-hotel-conceptualxlobbies
    step: xlobbies
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
