apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xlobbies.scalebeyond.rejekts.io
spec:
  group: scalebeyond.rejekts.io
  names:
    categories:
    - crossplane
    kind: XLobby
    plural: xlobbies
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        description: XLobby is the Schema for the XLobby API.
        properties:
          spec:
            description: XLobbySpec defines the desired state of XLobby.
            properties:
              parameters:
                properties:
                  wing:
                    type: string
                type: object
            type: object
          status:
            description: XLobbyStatus defines the observed state of XLobby.
            type: object
        required:
        - spec
        type: object
    served: true
