name: CI

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch:
    inputs:
      version:
        description: Package version (e.g. v0.1.0)
        required: false

env:
  UP_API_TOKEN: ${{ secrets.UP_API_TOKEN }}
  UP_ORG: ${{ secrets.UP_ORG }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install up
        uses: upbound/action-up@v1
        with:
          skip-login: true

      - name: Login
        if: env.UP_API_TOKEN != ''
        run: up login -t ${{ secrets.UP_API_TOKEN }} --organization ${{ secrets.UP_ORG }}

      - name: Build
        if: env.UP_API_TOKEN != ''
        run: up project build

      - name: Login to xpkg with robot
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: xpkg.upbound.io
          username: ${{ secrets.UP_API_ID }}
          password: ${{ secrets.UP_API_TOKEN }}

      - name: Push
        if: env.UP_API_TOKEN != ''
        run: |
          if [[ -n "${{ inputs.version }}" ]]; then
            up project push -t "${{ inputs.version }}"
          else
            up project push
          fi
